import type { ScreenFactory } from '@/app/Router';
import { el, svg } from '@/core/dom';
import { topBar } from '@/components/topbar';
import { leoSVG } from '@/characters/leo';
import { audio } from '@/audio/AudioEngine';
import { db, type LeoLabRecord } from '@/storage/db';
import { applyOutcome, computeMastery, type Stats } from '@/progress/progression';

type LabSpec={id:string;title:string;intro:string;art:string;question:string;options:{label:string;correct:boolean;feedback:string}[]};
const SPECS:Record<string,LabSpec>={
 carnivoras:{id:'carnivoras',title:'Plantas carnívoras',intro:'Observe luz, água e alimento. Mude apenas um fator por vez.',art:'<rect x="25" y="175" width="310" height="35" rx="12" fill="#B98C68"/><g id="plant" class="tappable" transform="translate(180 155)"><path d="M0 40V-40" stroke="#5C9855" stroke-width="12"/><path d="M0-35C-65-85-90-20-18 8C-5-10 0-22 0-35Z" fill="#79B86A" stroke="#467A42" stroke-width="5"/><path d="M0-35C65-85 90-20 18 8C5-10 0-22 0-35Z" fill="#79B86A" stroke="#467A42" stroke-width="5"/><path d="M-52-42l18 15m86-15-18 15" stroke="#E9E0C5" stroke-width="4"/></g><circle cx="285" cy="65" r="35" fill="#F3D778"/>',question:'A planta recebeu insetos, mas ficou em local escuro. Qual variável testar primeiro?',options:[{label:'Aumentar a luz mantendo água e substrato iguais',correct:true,feedback:'Correto: insetos fornecem nutrientes, mas não substituem a luz da fotossíntese.'},{label:'Dar mais insetos e trocar toda a água',correct:false,feedback:'Duas variáveis mudariam ao mesmo tempo.'},{label:'Tocar várias vezes nas armadilhas',correct:false,feedback:'Fechar armadilhas gasta energia sem garantir alimento.'}]},
 invertebrados:{id:'invertebrados',title:'Invertebrados',intro:'Use patas, antenas, segmentos e concha para classificar.',art:'<g id="bug" class="tappable" transform="translate(120 145)"><ellipse rx="35" ry="55" fill="#725B49"/><path d="M-20-40l-45-35M20-40l45-35M-28-10l-55-10M28-10l55-10M-25 20l-50 35M25 20l50 35" stroke="#514339" stroke-width="7"/></g><g transform="translate(260 155)"><circle r="50" fill="#D06D68"/><path d="M0-50V50" stroke="#333" stroke-width="6"/><circle cx="-20" cy="-15" r="7"/><circle cx="20" cy="-15" r="7"/></g>',question:'Um animal tem oito patas e nenhuma antena. Em qual grupo ele entra?',options:[{label:'Aracnídeos',correct:true,feedback:'Correto: aranhas e escorpiões têm oito patas e não possuem antenas.'},{label:'Insetos',correct:false,feedback:'Insetos possuem seis patas e um par de antenas.'},{label:'Moluscos',correct:false,feedback:'Moluscos têm corpo mole e não possuem patas articuladas.'}]},
 axolotes:{id:'axolotes',title:'Axolotes',intro:'Observe brânquias, temperatura e comportamento.',art:'<g id="axo" class="tappable" transform="translate(190 145)"><ellipse rx="80" ry="38" fill="#EAB1C0"/><circle cx="-55" cy="-10" r="5"/><path d="M70 0q55-55 75 5q-35 25-75 15" fill="#EAB1C0"/><path d="M-50-24l-38-35M-45-8l-50-5M-48 10l-42 30M50-20l35-32M48 5l45 18" stroke="#C97891" stroke-width="8" stroke-linecap="round"/></g><path d="M30 225Q130 195 230 225T360 220" stroke="#5A9A89" stroke-width="10" fill="none"/>',question:'As brânquias ficaram curvadas e o axolote parou de comer. O que investigar primeiro?',options:[{label:'Temperatura e qualidade da água',correct:true,feedback:'Correto: calor e água inadequada podem causar estresse.'},{label:'Colocar mais peixes no aquário',correct:false,feedback:'Outros animais podem aumentar estresse e risco de ferimentos.'},{label:'Aumentar muito a iluminação',correct:false,feedback:'Axolotes preferem luz suave e locais para se esconder.'}]},
 metodo:{id:'metodo',title:'Método científico',intro:'Observe, formule hipótese, teste uma variável e conclua pelos dados.',art:'<g id="flask" class="tappable" transform="translate(200 150)"><path d="M-25-85H25M-12-85V-25L-70 70Q-80 90-55 95H55Q80 90 70 70L12-25V-85" stroke="#657C8C" stroke-width="10" fill="#B9DCE6"/><path d="M-55 48Q0 25 55 48L70 75Q75 90 55 92H-55Q-75 90-70 75Z" fill="#BDA8D7"/></g><circle cx="115" cy="75" r="12" fill="#F0CD77"/><circle cx="290" cy="80" r="9" fill="#E7A7B6"/>',question:'Para descobrir se mais luz faz uma planta crescer, qual é o melhor experimento?',options:[{label:'Duas plantas iguais, mudando somente a quantidade de luz',correct:true,feedback:'Correto: assim a luz é a variável testada e as demais condições ficam controladas.'},{label:'Uma planta com mais luz, água e fertilizante',correct:false,feedback:'Com várias mudanças, não saberemos qual causou o resultado.'},{label:'Observar uma planta uma única vez',correct:false,feedback:'É preciso comparação e observações repetidas.'}]}
};

function statsOf(r:LeoLabRecord|undefined):Stats{return {level:r?.level??1,attempts:r?.attempts??0,correct:r?.correct??0,hints:r?.hints??0,conclusions:r?.conclusions??0,recent:[]};}
export function investigationLab(id:string):ScreenFactory{return (host)=>{const spec=SPECS[id];if(!spec){window.location.hash='/leo';return;}let answered=false;let stats:Stats={level:1,attempts:0,correct:0,hints:0,conclusions:0,recent:[]};const art=el('div',{class:'scene__stage',style:'min-height:240px;background:#E4EFE8;'});art.appendChild(svg(`<svg viewBox="0 0 380 240" xmlns="http://www.w3.org/2000/svg" aria-label="${spec.title}">${spec.art}</svg>`));const feedback=el('div',{class:'panel',role:'status','aria-live':'polite'},[spec.intro]);const buttons=spec.options.map(o=>el('button',{class:'btn btn--peach',style:'width:100%;margin:.35rem 0;text-align:left;',onclick:async()=>{if(answered)return;answered=true;stats=applyOutcome(stats,{correct:o.correct,usedHint:false,concluded:o.correct});feedback.textContent=o.feedback;audio.effect(o.correct?'success':'pop',o.correct?520:220);void audio.speakText(o.feedback);const prev=await db.getLab(id);await db.putLab({labId:id,level:stats.level,correct:(prev?.correct??0)+(o.correct?1:0),wrong:(prev?.wrong??0)+(o.correct?0:1),attempts:(prev?.attempts??0)+1,hints:prev?.hints??0,experiments:(prev?.experiments??0)+1,conclusions:(prev?.conclusions??0)+(o.correct?1:0),masteryScore:computeMastery(stats),lastPlayed:Date.now()});await db.addEvent({area:'leo',kind:o.correct?'investigation-ok':'investigation-retry',ref:id,ts:Date.now()});setTimeout(()=>{answered=false;},900);}},[o.label]));void (async()=>{stats=statsOf(await db.getLab(id));})();host.appendChild(el('div',{class:'screen'},[topBar(spec.title,'/leo'),el('div',{style:'width:105px;margin:0 auto;'},[svg(leoSVG('think'))]),art,el('div',{class:'panel'},[el('h3',{},[spec.question]),...buttons]),feedback]));};}
